import type { SiteConfig, AppState, ServiceItem } from '@/types'

export const DEFAULT_CONFIG: SiteConfig = {
  companyLogo: '',
  companyName: 'Rootwell',
  primaryColor: '#00d4ff',
  accentColor: '#ff0066',
  heroBadgeText: '🚁 Drones Profesionales',
  tagline: 'Capturamos la emoción desde el cielo',
  heroSubtitle:
    'Drones profesionales para eventos deportivos en toda España y Europa. FPV Racing, cinematografía aérea y retransmisión en vivo.',
  stat1Num: '200+',
  stat1Label: 'Eventos Filmados',
  stat2Num: '15+',
  stat2Label: 'Países',
  stat3Num: '4K',
  stat3Label: 'Resolución',
  servicesTag: 'Servicios',
  servicesTitle: 'Soluciones completas de drones',
  servicesSubtitle: 'Ofrecemos soluciones completas de drones para todo tipo de eventos deportivos',
  galleryTag: 'Galería',
  galleryTitle: 'Nuestro trabajo en acción',
  gallerySubtitle: 'Más de 200 eventos filmados en toda Europa. Cada vuelo es una historia única.',
  videoTag: 'Showreel',
  videoTitle: 'Nuestro trabajo habla por sí solo',
  videoSubtitle: 'Más de 200 eventos filmados en toda Europa. Cada vuelo es una historia única.',
  videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  reviewsTag: 'Testimonios',
  reviewsTitle: 'Lo que dicen nuestros clientes',
  contactTag: 'Contacto',
  contactTitle: 'Hablemos de tu próximo evento',
  contactSubtitle: 'Cuéntanos sobre tu evento y te enviaremos un presupuesto personalizado en menos de 24 horas.',
  contactEmail: 'info@teffydron.es',
  whatsappNumber: '34600000000',
  serviceArea: 'España y Europa',
  guaranteedResponse: '24 horas',
  instagramUrl: 'https://instagram.com/teffydron',
  youtubeUrl: 'https://youtube.com/@teffydron',
  facebookUrl: 'https://facebook.com/teffydron',
  footerText: '© 2025 Rootwell. Todos los derechos reservados. | RGPD · Aviso Legal',
  heroVideoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  heroVideoPoster: 'https://images.unsplash.com/photo-1527977966861-9b05741b38f5?w=1920',
  navbarLinks: 'Servicios,Galería,Showreel,Reseñas,Contacto',
  eventTypes: 'Fútbol / Rugby / Hockey,Ciclismo / Triatlón,Atletismo / Maratón,Automovilismo / Motociclismo,Deportes acuáticos,Esquí / Snowboard,eSports / Gaming,Otro evento',
  certifications: 'Piloto certificado AESA (España),Licencia EASA categoría Específica,Seguro RC de 1M€,Registro operador UAS',
  footerServicesLinks: 'Eventos Deportivos,Retransmisión en Vivo,Fotografía Aérea,FPV Racing,Mapping 3D',
  footerCompanyLinks: 'Showreel,Galería,Reseñas,Contacto,Panel Admin',
  footerLegalLinks: 'Aviso Legal,Política de Privacidad,Política de Cookies,RGPD',
  privacyPolicyUrl: '#',
  legalNoticeUrl: '#',
  cookiesPolicyUrl: '#',
}

export const DEFAULT_SERVICES: ServiceItem[] = [
  {
    id: '1',
    icon: '🎥',
    title: 'Eventos Deportivos',
    description: 'Cobertura aérea profesional de competiciones, maratones, ciclismo, fútbol y cualquier evento deportivo. Perspectivas únicas que ninguna cámara en tierra puede capturar.',
    tag: 'Especialidad',
  },
  {
    id: '2',
    icon: '📡',
    title: 'Retransmisión en Vivo',
    description: 'Streaming en tiempo real con latencia mínima. Integración con OBS, YouTube Live y plataformas de broadcasting profesional.',
    tag: 'Streaming',
  },
  {
    id: '3',
    icon: '📸',
    title: 'Fotografía Aérea',
    description: 'Imágenes en 8K con drones de última generación. Perfecto para marketing deportivo, publicaciones y contenido para redes sociales.',
    tag: 'Fotografía',
  },
  {
    id: '4',
    icon: '🎯',
    title: 'FPV Racing',
    description: 'Drones FPV de alta velocidad para seguimiento de pilotos, ciclistas y atletas. La experiencia más inmersiva y emocionante del mercado.',
    tag: 'FPV',
  },
  {
    id: '5',
    icon: '🗺️',
    title: 'Mapping 3D',
    description: 'Cartografía y modelado 3D de instalaciones deportivas, estadios y recorridos. Ideal para planificación y análisis táctico.',
    tag: 'Tecnología',
  },
  {
    id: '6',
    icon: '🎬',
    title: 'Cinematografía',
    description: 'Producciones cinematográficas de alto nivel para documentales, spots publicitarios y contenido premium de eventos.',
    tag: 'Cine',
  },
]

export const DEFAULT_GALLERY = [
  {
    id: '1',
    src: 'https://images.unsplash.com/photo-1527977966861-9b05741b38f5?w=800',
    alt: 'Drone sobre estadio deportivo',
    category: 'deportes' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    src: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800',
    alt: 'FPV racing en circuito',
    category: 'fpv' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    src: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800',
    alt: 'Vista aérea de competición ciclista',
    category: 'deportes' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    src: 'https://images.unsplash.com/photo-1534481016308-0fca71578ae5?w=800',
    alt: 'Drone cinematográfico profesional',
    category: 'cinematica' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    src: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=800',
    alt: 'Vista aérea de maratón urbano',
    category: 'aerea' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    src: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800',
    alt: 'Evento deportivo nocturno',
    category: 'deportes' as const,
    createdAt: new Date().toISOString(),
  },
]

export const DEFAULT_REVIEWS = [
  {
    id: '1',
    author: 'Carlos Martínez',
    role: 'Director Deportivo — Club Atlético Madrid',
    content:
      'TeffyDron transformó la cobertura de nuestros partidos. La calidad de imagen es increíble y el equipo es extremadamente profesional. Totalmente recomendados.',
    rating: 5,
    avatar: 'CM',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    author: 'Sophie Dubois',
    role: 'Organizadora — Tour Ciclista Francia',
    content:
      'Contratamos a TeffyDron para el Tour y superaron todas las expectativas. Las imágenes aéreas dieron una dimensión completamente nueva al evento.',
    rating: 5,
    avatar: 'SD',
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    author: 'Marco Rossi',
    role: 'CEO — SportMedia Italia',
    content:
      'El mejor servicio de drones para eventos que hemos contratado en toda Europa. Rápidos, profesionales y con tecnología de última generación.',
    rating: 5,
    avatar: 'MR',
    createdAt: new Date().toISOString(),
  },
]

export const INITIAL_STATE: AppState = {
  siteConfig: DEFAULT_CONFIG,
  services: DEFAULT_SERVICES,
  gallery: DEFAULT_GALLERY,
  reviews: DEFAULT_REVIEWS,
  messages: [],
}
